version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/usr/share/nginx/html
    links:
      - php_app
      
  php_app:
    container_name: php_app
    build: .
    volumes:
      - ./api:/usr/share/nginx/html

  data_base_maria_db_10_6:
    container_name: data_base_maria_db_10_6
    image: mariadb:10.6.14-focal
    ports: 
      - "3306:3306"
    environment:
      MYSQL_HOST: 'data_base_maria_db_10_6'
      MYSQL_DATABASE: 'Na_ponta_do_lapis'
      MYSQL_ROOT_PASSWORD: 'toor123'
    volumes: 
      - ./dataBase:/var/lib/mysql
