version: "3"

networks:
  backend:

services:
  nginx:
    networks: 
      - backend
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/usr/share/nginx/html
      
  php_app:
    networks: 
      - backend
    container_name: php_app
    build: .
    volumes:
      - ./api:/usr/share/nginx/html
    environment:
      MYSQL_CONECTION: 'mysql'
      MYSQL_HOST: 'mariadb'
      MYSQL_PORT: '3306'
      MYSQL_DATABASE: 'tabela_teste'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'

  mariadb:
    networks: 
      - backend
    container_name: mariadb
    image: mariadb:10
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'tabela_teste'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_PASSWORD: 'root'
    volumes: 
      - ./dataBase:/var/lib/mysql

